spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/testRealm

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/testRealm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: haX3SvrMhZxGyjPS3HsjeKqOlmA91fn7
            scope: openid



server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE